version: '3.8'

services:
  # MySQL DB services
  # -----------------------------------------
  mysql:
    image: mysql:8
    container_name: mysql-golfclub
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: MyJQL123!
      MYSQL_DATABASE: golfclub_db

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
# -----------------------------------------
# Docker is named volume for persistent data

volumes:
  mysql-data:
